### ISSUE TITLE
deploy somewhere

### ISSUE THREAD

**Issue by segler-alex** [kyjus25/radiobrowser#1]
Hi,

it would be very cool for this project to be deployed somewhere
could you create a deployment?
i really like your project

there are a lot of free possibilities:
* github pages
* https://surge.sh/
* https://www.netlify.com
* https://zeit.co/

**Comment by kyjus25** [comment]
Thanks sir! I am very humbled that you like the project!

I will work on getting it hosted somewhere tomorrow as currently it is still running off my Raspberry Pi.

**Comment by kyjus25** [comment]
The site has been deployed to GitHub Pages at https://radio-browser.live

I am holding off on closing this issue until I can correct the SSL cert issue with my ICY metadata fetcher

**Comment by kyjus25** [comment]
ICY metadata cert issue is fixed! Closing the issue
