### ISSUE TITLE
send countrycode on new station

### ISSUE THREAD

**Issue by segler-alex** [kyjus25/radiobrowser#2]
the api is slowly moving away from the country field. it is deprecated now. new stations should add a countrycode field with the official 2 letter code. in the main radiobrowser gui i use an external server for getting an up to date json listing of worldwide country codes from United nations (https://restcountries.eu/) but any one could be used.

**Comment by kyjus25** [comment]
Thanks for the heads up! I will use the same endpoint and follow suit

**Comment by kyjus25** [comment]
@segler-alex this has been updated added!

https://radio-browser.live/#/stations/new
